# Generated by Django 2.2 on 2019-06-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='department',
            field=models.CharField(choices=[('tech', 'Tech'), ('mplab', 'Mplab'), ('acadmey', 'Acadmey')], default='DEFAULT VALUE', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='operations',
            field=models.CharField(choices=[('hall', 'Hall'), ('utensils', 'Utensils')], default='DEFAULT VALUE', max_length=50),
        ),
    ]
