# Generated by Django 2.2.2 on 2019-06-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_auto_20190607_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('department', models.CharField(choices=[('tech', 'Tech'), ('mplab', 'Mplab'), ('acadmey', 'Acadmey')], default='DEFAULT VALUE', max_length=50)),
                ('leavetype', models.CharField(choices=[('fullday', 'Fullday'), ('halfday', 'Halfday')], default='DEFAULT VALUE', max_length=50)),
                ('supervisoremail', models.EmailField(max_length=254)),
                ('teamleademail', models.EmailField(max_length=254)),
                ('numberofdays', models.DateTimeField()),
            ],
        ),
        migrations.RenameModel(
            old_name='post',
            new_name='operation',
        ),
    ]
